[package]
name = "monero-burn"
version = "0.1.0"
authors = ["Kostis Karantias <kkarantias@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monero = "0.5.0"